# Generated by Django 4.1.2 on 2022-11-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0054_bookingpropertytype_alter_bookingnow_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytypefilter',
            name='project_type_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_filters', to='indexApp.projecttypefilter'),
        ),
    ]
